import type { JapaneseVerb } from "@/lib/types";

export const N5Verbs: JapaneseVerb[] = [
  {
    dictionary: "上げる",
    kana: "あげる",
    meaning: "to raise, to elevate",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "走る",
    kana: "はしる",
    meaning: "to run, to rush",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "飲む",
    kana: "のむ",
    meaning: "to drink, to swallow",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "成る",
    kana: "なる",
    meaning: "to become, to get, to grow",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "有る",
    kana: "ある",
    meaning: "to be, to exist, to live",
    type: "godan",
    transitivity: "intransitive",
    irregularForms: {
      "present indicative-affirmative-plain": ["ある", "ある"],
      "present indicative-affirmative-polite": ["あります", "あります"],
      "present indicative-negative-plain": ["ない", "ない"],
      "present indicative-negative-polite": ["ありません", "ありません"],
    },
  },
  {
    dictionary: "言う",
    kana: "いう",
    meaning: "to say, to utter",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "出来る",
    kana: "できる",
    meaning: "to be able to do, to be possible",
    type: "ichidan",
    transitivity: "intransitive",
  },
  {
    dictionary: "見る",
    kana: "みる",
    meaning: "to see, to look",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "知る",
    kana: "しる",
    meaning: "to know, to be aware (of)",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "持つ",
    kana: "もつ",
    meaning: "to hold (in one's hand), to take",
    type: "godan",
    transitivity: "transitive",
  },
];
