import type { JapaneseVerb } from "@/lib/types";

export const N1Verbs: JapaneseVerb[] = [
  {
    dictionary: "打ち明ける",
    kana: "うちあける",
    meaning: "to confide, to reveal",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "打ち切る",
    kana: "うちきる",
    meaning: "to terminate, to discontinue",
    type: "godan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "打ち込む",
    kana: "うちこむ",
    meaning: "to drive in, to devote oneself to",
    type: "godan",
    ending: "mu",
    transitivity: "intransitive",
  },
  {
    dictionary: "打ち消す",
    kana: "うちけす",
    meaning: "to deny, to negate",
    type: "godan",
    ending: "su",
    transitivity: "intransitive",
  },
  {
    dictionary: "打ち破る",
    kana: "うちやぶる",
    meaning: "to break, to defeat",
    type: "godan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "打ち解ける",
    kana: "うちとける",
    meaning: "to open up, to become friendly",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "打ち合わせる",
    kana: "うちあわせる",
    meaning: "to arrange, to coordinate",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "打ち勝つ",
    kana: "うちかつ",
    meaning: "to overcome, to prevail",
    type: "godan",
    ending: "tsu",
    transitivity: "intransitive",
  },
  {
    dictionary: "打ち砕く",
    kana: "うちくだく",
    meaning: "to smash, to crush",
    type: "godan",
    ending: "ku",
    transitivity: "intransitive",
  },
  {
    dictionary: "打ち立てる",
    kana: "うちたてる",
    meaning: "to establish, to set up",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
];
