import type { JapaneseVerb } from "@/lib/types";

export const N5Verbs: JapaneseVerb[] = [
  {
    dictionary: "上げる",
    kana: "あげる",
    meaning: "to raise, to elevate",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "走る",
    kana: "はしる",
    meaning: "to run, to rush",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "飲む",
    kana: "のむ",
    meaning: "to drink, to swallow",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "成る",
    kana: "なる",
    meaning: "to become, to get, to grow",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "有る",
    kana: "ある",
    meaning: "to be, to exist, to live",
    type: "godan",
    transitivity: "intransitive",
    irregularForms: {
      "present indicative-affirmative-plain": ["ある", "ある"],
      "present indicative-affirmative-polite": ["あります", "あります"],
      "present indicative-negative-plain": ["ない", "ない"],
      "present indicative-negative-polite": ["ありません", "ありません"],
    },
  },
  {
    dictionary: "言う",
    kana: "いう",
    meaning: "to say, to utter",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "出来る",
    kana: "できる",
    meaning: "to be able to do, to be possible",
    type: "ichidan",
    transitivity: "intransitive",
  },
  {
    dictionary: "見る",
    kana: "みる",
    meaning: "to see, to look",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "知る",
    kana: "しる",
    meaning: "to know, to be aware (of)",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "持つ",
    kana: "もつ",
    meaning: "to hold (in one's hand), to take",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "話す",
    kana: "はなす",
    meaning: "to talk, to speak",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "買う",
    kana: "かう",
    meaning: "to buy, to purchase",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "読む",
    kana: "よむ",
    meaning: "to read",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "出る",
    kana: "でる",
    meaning: "to come out, to go out",
    type: "ichidan",
    transitivity: "intransitive",
  },
  {
    dictionary: "取る",
    kana: "とる",
    meaning: "to take, to pick up",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "使う",
    kana: "つかう",
    meaning: "to use, to make use of",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "待つ",
    kana: "まつ",
    meaning: "to wait, to wait for",
    type: "godan",
    transitivity: "both",
  },
  {
    dictionary: "作る",
    kana: "つくる",
    meaning: "to make, to create",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "行く",
    kana: "いく",
    meaning: "to go, to travel",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "乗る",
    kana: "のる",
    meaning: "to ride, to get on",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "終わる",
    kana: "おわる",
    meaning: "to end, to finish",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "寝る",
    kana: "ねる",
    meaning: "to sleep",
    type: "ichidan",
    transitivity: "intransitive",
  },
  {
    dictionary: "泳ぐ",
    kana: "およぐ",
    meaning: "to swim",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "出す",
    kana: "だす",
    meaning: "to take out, to get out",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "立つ",
    kana: "たつ",
    meaning: "to stand, to be on one's feet",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "着る",
    kana: "きる",
    meaning: "to put on, to wear",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "呼ぶ",
    kana: "よぶ",
    meaning: "to call, to summon",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "掛ける",
    kana: "かける",
    meaning: "to hang up, to put on",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "歌う",
    kana: "うたう",
    meaning: "to sing",
    type: "godan",
    transitivity: "both",
  },
  {
    dictionary: "上る",
    kana: "のぼる",
    meaning: "to climb, to ascend",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "頼む",
    kana: "たのむ",
    meaning: "to ask for, to request",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "借りる",
    kana: "かりる",
    meaning: "to borrow, to lend",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "飛ぶ",
    kana: "とぶ",
    meaning: "to fly",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "売る",
    kana: "うる",
    meaning: "to sell",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "休む",
    kana: "やすむ",
    meaning: "to rest, to take a break",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "降りる",
    kana: "おりる",
    meaning: "to fall, to rain",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "止まる",
    kana: "とまる",
    meaning: "to stop, to stop",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "洗う",
    kana: "あらう",
    meaning: "to wash, to clean",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "切る",
    kana: "きる",
    meaning: "to cut, to slice",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "返す",
    kana: "かえす",
    meaning: "to return, to give back",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "押す",
    kana: "おす",
    meaning: "to press, to push",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "勤める",
    kana: "つとめる",
    meaning: "to work, to serve",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "張る",
    kana: "はる",
    meaning: "to stretch, to stick, to hang",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "渡す",
    kana: "わたす",
    meaning: "to pass, to give",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "浴びる",
    kana: "あびる",
    meaning: "to bathe, to bathe in",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "撮る",
    kana: "とる",
    meaning: "to take, to photograph",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "締める",
    kana: "しめる",
    meaning: "to tie, to close, to fasten",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "居る",
    kana: "いる",
    meaning: "to be, to stay, to exist",
    type: "ichidan",
    transitivity: "intransitive"
  },
  {
    dictionary: "会う",
    kana: "あう",
    meaning: "to meet, to see",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "分かる",
    kana: "わかる",
    meaning: "to understand, to know",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "聞く",
    kana: "きく",
    meaning: "to listen, to hear",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "書く",
    kana: "かく",
    meaning: "to write",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "入る",
    kana: "はいる",
    meaning: "to enter, to go in",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "置く",
    kana: "おく",
    meaning: "to put, to place",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "住む",
    kana: "すむ",
    meaning: "to live, to stay",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "食べる",
    kana: "たべる",
    meaning: "to eat",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "歩く",
    kana: "あるく",
    meaning: "to walk",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "働く",
    kana: "はたらく",
    meaning: "to work",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "着く",
    kana: "つく",
    meaning: "to arrive, to reach",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "教える",
    kana: "おしえる",
    meaning: "to teach, to instruct",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "降る",
    kana: "ふる",
    meaning: "to rain, to fall",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "死ぬ",
    kana: "しぬ",
    meaning: "to die",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "帰る",
    kana: "かえる",
    meaning: "to return, to go back",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "出かける",
    kana: "でかける",
    meaning: "to go out, to leave",
    type: "ichidan",
    transitivity: "intransitive",
  },
  {
    dictionary: "掛かる",
    kana: "かかる",
    meaning: "to take, to spend",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "起きる",
    kana: "おきる",
    meaning: "to wake up, to get up",
    type: "ichidan",
    transitivity: "intransitive",
  },
  {
    dictionary: "座る",
    kana: "すわる",
    meaning: "to sit, to take a seat",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "入れる",
    kana: "いれる",
    meaning: "to put, to place",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "疲れる",
    kana: "つかれる",
    meaning: "to be tired, to be exhausted",
    type: "ichidan",
    transitivity: "intransitive",
  },
  {
    dictionary: "開ける",
    kana: "あける",
    meaning: "to open",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "見せる",
    kana: "みせる",
    meaning: "to show, to exhibit",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "違う",
    kana: "ちがう",
    meaning: "to differ, to be wrong",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "付ける",
    kana: "つける",
    meaning: "to attach, to join",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "覚える",
    kana: "おぼえる",
    meaning: "to memorize, to remember",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "困る",
    kana: "こまる",
    meaning: "to be troubled, to have difficulty",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "生まれる",
    kana: "うまれる",
    meaning: "to be born",
    type: "ichidan",
    transitivity: "intransitive",
  },
  {
    dictionary: "始まる",
    kana: "はじまる",
    meaning: "to start, to begin",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "貸す",
    kana: "かす",
    meaning: "to lend, to loan",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "弾く",
    kana: "ひく",
    meaning: "to play, to play the guitar",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "遊ぶ",
    kana: "あそぶ",
    meaning: "to play, to play",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "無くす",
    kana: "なくす",
    meaning: "to lose, to get rid of",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "渡る",
    kana: "わたる",
    meaning: "to cross, to pass",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "消す",
    kana: "けす",
    meaning: "to erase, to delete",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "閉める",
    kana: "しめる",
    meaning: "to close, to shut",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "消える",
    kana: "きえる",
    meaning: "to disappear, to vanish",
    type: "ichidan",
    transitivity: "intransitive",
  },
  {
    dictionary: "晴れる",
    kana: "はれる",
    meaning: "to clear up, to become sunny",
    type: "ichidan",
    transitivity: "intransitive",
  },
  {
    dictionary: "曲がる",
    kana: "まがる",
    meaning: "to bend, to curve",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "吹く",
    kana: "ふく",
    meaning: "to blow, to blow",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "引く",
    kana: "ひく",
    meaning: "to pull, to draw",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "習う",
    kana: "ならう",
    meaning: "to learn, to study",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "脱ぐ",
    kana: "ぬぐ",
    meaning: "to take off, to remove",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "並ぶ",
    kana: "ならぶ",
    meaning: "to line up, to rival",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "吸う",
    kana: "すう",
    meaning: "to smoke, to smoke",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "閉まる",
    kana: "しまる",
    meaning: "to close, to shut",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "咲く",
    kana: "さく",
    meaning: "to bloom, to bloom",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "並べる",
    kana: "ならべる",
    meaning: "to arrange, to line up",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "曇る",
    kana: "くもる",
    meaning: "to cloud, to be cloudy",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "磨く",
    kana: "みがく",
    meaning: "to polish, to shine",
    type: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "鳴く",
    kana: "なく",
    meaning: "to sound, to call",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "差す",
    kana: "さす",
    meaning: "to shine, to be visible",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "答える",
    kana: "こたえる",
    meaning: "to answer, to respond",
    type: "ichidan",
    transitivity: "transitive",
  },
  {
    dictionary: "要る",
    kana: "いる",
    meaning: "to be necessary, to be required",
    type: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "する",
    kana: "する",
    meaning: "to do, to carry out",
    type: "irregular",
    transitivity: "transitive",
    irregularForms: {
      "present indicative-affirmative-plain": ["する", "する"],
      "present indicative-negative-plain": ["しない", "しない"],
      "present indicative-affirmative-polite": ["します", "します"],
      "present indicative-negative-polite": ["しません", "しません"],
      "past indicative-affirmative-plain": ["した", "した"],
      "past indicative-negative-plain": ["しなかった", "しなかった"],
      "past indicative-affirmative-polite": ["しました", "しました"],
      "past indicative-negative-polite": ["しませんでした", "しませんでした"],
      "presumptive-affirmative-plain": ["しよう", "しよう"],
      "presumptive-negative-plain": ["しないだろう", "しないだろう"],
      "presumptive-affirmative-polite": ["しましょう", "しましょう"],
      "presumptive-negative-polite": ["しないでしょう", "しないでしょう"],
      "past presumptive-affirmative-plain": ["したろう", "したろう"],
      "past presumptive-negative-plain": ["しなかっただろう", "しなかっただろう"],
      "past presumptive-affirmative-polite": ["しましたろう", "しましたろう"],
      "past presumptive-negative-polite": ["しなかったでしょう", "しなかったでしょう"],
      "present progressive-affirmative-polite": ["しています", "しています"],
      "present progressive-negative-polite": ["していません", "していません"],
      "past progressive-affirmative-polite": ["していました", "していました"],
      "past progressive-negative-polite": ["していませんでした", "していませんでした"],
      "conditional ba-affirmative-plain": ["するば", "すれば"],
      "conditional ba-negative-plain": ["しなければ", "しなければ"],
      "conditional ba-affirmative-polite": ["しませば", "しませば"],
      "conditional ba-negative-polite": ["しませんなら", "しませんなら"],
      "conditional tara-affirmative-plain": ["したら", "したら"],
      "conditional tara-negative-plain": ["しなかったら", "しなかったら"],
      "conditional tara-affirmative-polite": ["しましたら", "しましたら"],
      "conditional tara-negative-polite": ["しませんでしたら", "しませんでしたら"],
      "potential-affirmative-plain": ["できる", "できる"],
      "potential-negative-plain": ["できない", "できない"],
      "potential-affirmative-polite": ["できます", "できます"],
      "potential-negative-polite": ["できません", "できません"],
      "causative-affirmative-plain": ["させる", "させる"],
      "imperative-affirmative-plain": ["しろ", "しろ"],
      "imperative-negative-plain": ["するな", "するな"],
      "imperative-affirmative-polite": ["してください", "してください"],
      "imperative-negative-polite": ["しないでください", "しないでください"],
      "te form-affirmative-plain": ["して", "して"],
      "te form-negative-plain": ["しなくて", "しなくて"],
      "passive-affirmative-plain": ["される", "される"],
    },
  },
  {
    dictionary: "来る",
    kana: "くる",
    meaning: "to come, to arrive",
    type: "irregular",
    transitivity: "intransitive",
  },
];
