import type { JapaneseVerb } from "@/lib/types";

export const N5Verbs: JapaneseVerb[] = [
  {
    dictionary: "会う",
    kana: "あう",
    meaning: "to meet",
    type: "godan",
    ending: "u",
    transitivity: "intransitive",
  },
  {
    dictionary: "開く",
    kana: "あく",
    meaning: "to open",
    type: "godan",
    ending: "ku",
    transitivity: "intransitive",
  },
  {
    dictionary: "開ける",
    kana: "あける",
    meaning: "to open",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "あげる",
    kana: "あげる",
    meaning: "to give",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "遊ぶ",
    kana: "あそぶ",
    meaning: "to play",
    type: "godan",
    ending: "bu",
    transitivity: "intransitive",
  },
  {
    dictionary: "浴びる",
    kana: "あびる",
    meaning: "to take a shower",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "洗う",
    kana: "あらう",
    meaning: "to wash",
    type: "godan",
    ending: "u",
    transitivity: "transitive",
  },
  {
    dictionary: "有る",
    kana: "ある",
    meaning: "to be, to exist (inanimate objects)",
    type: "irregular",
    irregularForms: new Map([
      [{ tense: "present", polarity: "affirmative", formality: "plain" }, "ある"],
      [{ tense: "present", polarity: "affirmative", formality: "polite" }, "あります"],
      [{ tense: "present", polarity: "negative", formality: "plain" }, "ない"],
      [{ tense: "present", polarity: "negative", formality: "polite" }, "ありません"],
      [{ tense: "past", polarity: "affirmative", formality: "plain" }, "あった"],
      [{ tense: "past", polarity: "affirmative", formality: "polite" }, "ありました"],
      [{ tense: "past", polarity: "negative", formality: "plain" }, "なかった"],
      [{ tense: "past", polarity: "negative", formality: "polite" }, "ありませんでした"]
    ]),
    regularPattern: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "歩く",
    kana: "あるく",
    meaning: "to walk",
    type: "godan",
    ending: "ku",
    transitivity: "intransitive",
  },
  {
    dictionary: "言う",
    kana: "いう",
    meaning: "to say, to tell",
    type: "godan",
    ending: "u",
    transitivity: "transitive",
  },
  {
    dictionary: "行く",
    kana: "いく",
    meaning: "to go",
    type: "godan",
    ending: "ku",
    transitivity: "intransitive",
  },
  {
    dictionary: "要る",
    kana: "いる",
    meaning: "to need, must have, be required",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "居る",
    kana: "いる",
    meaning: "to be, to exist (animate objects)",
    type: "ichidan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "入れる",
    kana: "いれる",
    meaning: "to insert, to put in",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "歌う",
    kana: "うたう",
    meaning: "to sing",
    type: "godan",
    ending: "u",
    transitivity: "transitive",
  },
  {
    dictionary: "生まれる",
    kana: "うまれる",
    meaning: "to be born",
    type: "ichidan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "売る",
    kana: "うる",
    meaning: "to sell",
    type: "godan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "起きる",
    kana: "おきる",
    meaning: "to get up, to stand up",
    type: "ichidan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "おく",
    kana: "おく",
    meaning: "to put",
    type: "godan",
    ending: "ku",
    transitivity: "transitive",
  },
  {
    dictionary: "送る",
    kana: "おくる",
    meaning: "to send",
    type: "godan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "押す",
    kana: "おす",
    meaning: "to push",
    type: "godan",
    ending: "su",
    transitivity: "transitive",
  },
  {
    dictionary: "覚える",
    kana: "おぼえる",
    meaning: "to memorize, to remember",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "泳ぐ",
    kana: "およぐ",
    meaning: "to swim",
    type: "godan",
    ending: "gu",
    transitivity: "intransitive",
  },
  {
    dictionary: "降りる",
    kana: "おりる",
    meaning: "to get off",
    type: "ichidan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "終わる",
    kana: "おわる",
    meaning: "to end",
    type: "godan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "買う",
    kana: "かう",
    meaning: "to buy",
    type: "godan",
    ending: "u",
    transitivity: "transitive",
  },
  {
    dictionary: "返す",
    kana: "かえす",
    meaning: "to return an object",
    type: "godan",
    ending: "su",
    transitivity: "transitive",
  },
  {
    dictionary: "帰る",
    kana: "かえる",
    meaning: "to return home",
    type: "godan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "かかる",
    kana: "かかる",
    meaning: "to take time or money",
    type: "godan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "書く",
    kana: "かく",
    meaning: "to write",
    type: "godan",
    ending: "ku",
    transitivity: "transitive",
  },
  {
    dictionary: "かける",
    kana: "かける",
    meaning: "to put on (glasses)",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "かける",
    kana: "かける",
    meaning: "to make a phone call",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "貸す",
    kana: "かす",
    meaning: "to lend",
    type: "godan",
    ending: "su",
    transitivity: "transitive",
  },
  {
    dictionary: "冠る",
    kana: "かぶる",
    meaning: "to put on a hat",
    type: "godan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "借りる",
    kana: "かりる",
    meaning: "to borrow",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "消える",
    kana: "きえる",
    meaning: "to go out, to vanish",
    type: "ichidan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "聞く",
    kana: "きく",
    meaning: "to listen, to ask",
    type: "godan",
    ending: "ku",
    transitivity: "transitive",
  },
  {
    dictionary: "切る",
    kana: "きる",
    meaning: "to cut",
    type: "godan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "着る",
    kana: "きる",
    meaning: "to wear, to put on",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "来る",
    kana: "くる",
    meaning: "to come",
    type: "irregular",
    irregularForms: new Map([
      [{ tense: "present", polarity: "affirmative", formality: "plain" }, "くる"],
      [{ tense: "present", polarity: "affirmative", formality: "polite" }, "きます"],
      [{ tense: "present", polarity: "negative", formality: "plain" }, "くない"],
      [{ tense: "present", polarity: "negative", formality: "polite" }, "きません"],
      [{ tense: "past", polarity: "affirmative", formality: "plain" }, "きた"],
      [{ tense: "past", polarity: "affirmative", formality: "polite" }, "きました"],
      [{ tense: "past", polarity: "negative", formality: "plain" }, "きなかった"],
      [{ tense: "past", polarity: "negative", formality: "polite" }, "きませんでした"],
    ]),
    regularPattern: "godan",
    transitivity: "intransitive",
  },
  {
    dictionary: "消す",
    kana: "けす",
    meaning: "to turn off, to switch off",
    type: "godan",
    ending: "su",
    transitivity: "transitive",
  },
  {
    dictionary: "答える",
    kana: "こたえる",
    meaning: "to answer",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "困る",
    kana: "こまる",
    meaning: "to be in trouble",
    type: "godan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "咲く",
    kana: "さく",
    meaning: "to blossom",
    type: "godan",
    ending: "ku",
    transitivity: "intransitive",
  },
  {
    dictionary: "さす",
    kana: "さす",
    meaning: "to open an umbrella",
    type: "godan",
    ending: "su",
    transitivity: "transitive",
  },
  {
    dictionary: "死ぬ",
    kana: "しぬ",
    meaning: "to die, to pass away",
    type: "godan",
    ending: "nu",
    transitivity: "intransitive",
  },
  {
    dictionary: "閉まる",
    kana: "しまる",
    meaning: "to close",
    type: "godan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "閉める",
    kana: "しめる",
    meaning: "to close",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "締める",
    kana: "しめる",
    meaning: "to fasten a belt",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "知る",
    kana: "しる",
    meaning: "to know",
    type: "godan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "吸う",
    kana: "すう",
    meaning: "to breathe, to smoke",
    type: "godan",
    ending: "u",
    transitivity: "transitive",
  },
  {
    dictionary: "住む",
    kana: "すむ",
    meaning: "to live, to reside",
    type: "godan",
    ending: "mu",
    transitivity: "intransitive",
  },
  {
    dictionary: "する",
    kana: "する",
    meaning: "to do",
    type: "irregular",
    irregularForms: new Map([
      [{ tense: "present", polarity: "affirmative", formality: "plain" }, "する"],
      [{ tense: "present", polarity: "affirmative", formality: "polite" }, "します"],
      [{ tense: "present", polarity: "negative", formality: "plain" }, "しない"],
      [{ tense: "present", polarity: "negative", formality: "polite" }, "しません"],
      [{ tense: "past", polarity: "affirmative", formality: "plain" }, "した"],
      [{ tense: "past", polarity: "affirmative", formality: "polite" }, "しました"],
      [{ tense: "past", polarity: "negative", formality: "plain" }, "しなかった"],
      [{ tense: "past", polarity: "negative", formality: "polite" }, "しませんでした"]
    ]),
    regularPattern: "godan",
    transitivity: "transitive",
  },
  {
    dictionary: "座る",
    kana: "すわる",
    meaning: "to sit",
    type: "godan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "出す",
    kana: "だす",
    meaning: "to take out, to hand in",
    type: "godan",
    ending: "su",
    transitivity: "transitive",
  },
  {
    dictionary: "立つ",
    kana: "たつ",
    meaning: "to stand",
    type: "godan",
    ending: "tsu",
    transitivity: "intransitive",
  },
  {
    dictionary: "頼む",
    kana: "たのむ",
    meaning: "to ask, to request",
    type: "godan",
    ending: "mu",
    transitivity: "transitive",
  },
  {
    dictionary: "食べる",
    kana: "たべる",
    meaning: "to eat",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "違う",
    kana: "ちがう",
    meaning: "to be different",
    type: "godan",
    ending: "u",
    transitivity: "intransitive",
  },
  {
    dictionary: "使う",
    kana: "つかう",
    meaning: "to use",
    type: "godan",
    ending: "u",
    transitivity: "transitive",
  },
  {
    dictionary: "疲れる",
    kana: "つかれる",
    meaning: "to get tired",
    type: "ichidan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "着く",
    kana: "つく",
    meaning: "to arrive",
    type: "godan",
    ending: "ku",
    transitivity: "intransitive",
  },
  {
    dictionary: "作る",
    kana: "つくる",
    meaning: "to make, to produce",
    type: "godan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "点ける",
    kana: "つける",
    meaning: "to turn on",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "勤める",
    kana: "つとめる",
    meaning: "to work for someone",
    type: "ichidan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "出かける",
    kana: "でかける",
    meaning: "to go out",
    type: "ichidan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "できる",
    kana: "できる",
    meaning: "to be able to",
    type: "ichidan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "出る",
    kana: "でる",
    meaning: "to leave, to go out",
    type: "ichidan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "飛ぶ",
    kana: "とぶ",
    meaning: "to fly",
    type: "godan",
    ending: "bu",
    transitivity: "intransitive",
  },
  {
    dictionary: "止まる",
    kana: "とまる",
    meaning: "to stop",
    type: "godan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "勉強する",
    kana: "べんきょうする",
    meaning: "to study",
    type: "godan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "取る",
    kana: "とる",
    meaning: "to take",
    type: "godan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "手伝う",
    kana: "てつだう",
    meaning: "to help",
    type: "godan",
    ending: "u",
    transitivity: "transitive",
  },
  {
    dictionary: "撮る",
    kana: "とる",
    meaning: "to take (a photo)",
    type: "godan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "直す",
    kana: "なおす",
    meaning: "to repair, to fix",
    type: "godan",
    ending: "su",
    transitivity: "transitive",
  },
  {
    dictionary: "鳴く",
    kana: "なく",
    meaning: "to cry, to sing (birds)",
    type: "godan",
    ending: "ku",
    transitivity: "intransitive",
  },
  {
    dictionary: "鳴る",
    kana: "なる",
    meaning: "to sound, to ring-3",
    type: "godan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "習う",
    kana: "ならう",
    meaning: "to learn",
    type: "godan",
    ending: "u",
    transitivity: "transitive",
  },
  {
    dictionary: "寝る",
    kana: "ねる",
    meaning: "to sleep",
    type: "ichidan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "登る",
    kana: "のぼる",
    meaning: "to climb up",
    type: "godan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "飲む",
    kana: "のむ",
    meaning: "to drink",
    type: "godan",
    ending: "mu",
    transitivity: "transitive",
  },
  {
    dictionary: "乗る",
    kana: "のる",
    meaning: "to take, to ride",
    type: "godan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "入る",
    kana: "はいる",
    meaning: "to enter",
    type: "godan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "履く",
    kana: "はく",
    meaning: "to put on shoes",
    type: "godan",
    ending: "ku",
    transitivity: "transitive",
  },
  {
    dictionary: "始まる",
    kana: "はじまる",
    meaning: "to begin, to start",
    type: "godan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "走る",
    kana: "はしる",
    meaning: "to run",
    type: "godan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "働く",
    kana: "はたらく",
    meaning: "to work",
    type: "godan",
    ending: "ku",
    transitivity: "intransitive",
  },
  {
    dictionary: "話す",
    kana: "はなす",
    meaning: "to talk, to speak, to tell",
    type: "godan",
    ending: "su",
    transitivity: "transitive",
  },
  {
    dictionary: "張る",
    kana: "はる",
    meaning: "to put something on, to stick",
    type: "godan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "晴れる",
    kana: "はれる",
    meaning: "to clear up",
    type: "ichidan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "引く",
    kana: "ひく",
    meaning: "to pull",
    type: "godan",
    ending: "ku",
    transitivity: "transitive",
  },
  {
    dictionary: "弾く",
    kana: "ひく",
    meaning: "to play an instrument",
    type: "godan",
    ending: "ku",
    transitivity: "transitive",
  },
  {
    dictionary: "吹く",
    kana: "ふく",
    meaning: "to blow (wind)",
    type: "godan",
    ending: "ku",
    transitivity: "intransitive",
  },
  {
    dictionary: "降る",
    kana: "ふる",
    meaning: "to fall (rain, snow)",
    type: "godan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "曲がる",
    kana: "まがる",
    meaning: "to turn",
    type: "godan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "待つ",
    kana: "まつ",
    meaning: "to wait",
    type: "godan",
    ending: "tsu",
    transitivity: "intransitive",
  },
  {
    dictionary: "磨く",
    kana: "みがく",
    meaning: "to polish, to brush",
    type: "godan",
    ending: "ku",
    transitivity: "transitive",
  },
  {
    dictionary: "見せる",
    kana: "みせる",
    meaning: "to show",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "見る",
    kana: "みる",
    meaning: "to see, to watch",
    type: "ichidan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "持つ",
    kana: "もつ",
    meaning: "to have, to own",
    type: "godan",
    ending: "tsu",
    transitivity: "transitive",
  },
  {
    dictionary: "休む",
    kana: "やすむ",
    meaning: "to rest",
    type: "godan",
    ending: "mu",
    transitivity: "intransitive",
  },
  {
    dictionary: "やる",
    kana: "やる",
    meaning: "to do",
    type: "godan",
    ending: "ru",
    transitivity: "transitive",
  },
  {
    dictionary: "呼ぶ",
    kana: "よぶ",
    meaning: "to call",
    type: "godan",
    ending: "bu",
    transitivity: "transitive",
  },
  {
    dictionary: "読む",
    kana: "よむ",
    meaning: "to read",
    type: "godan",
    ending: "mu",
    transitivity: "transitive",
  },
  {
    dictionary: "分かる",
    kana: "わかる",
    meaning: "to know, to understand",
    type: "godan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "忘れる",
    kana: "わすれる",
    meaning: "to forget",
    type: "ichidan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "渡す",
    kana: "わたす",
    meaning: "to hand over",
    type: "godan",
    ending: "su",
    transitivity: "transitive",
  },
  {
    dictionary: "渡る",
    kana: "わたる",
    meaning: "to cross",
    type: "godan",
    ending: "ru",
    transitivity: "intransitive",
  },
  {
    dictionary: "脱ぐ",
    kana: "ぬぐ",
    meaning: "to take off clothes",
    type: "godan",
    ending: "gu",
    transitivity: "transitive",
  },
];
